### ISSUE TITLE
Class 'Kalnoy\Nestedset\Node' not found

### ISSUE THREAD

**Issue by ergonomicus** [faustbrian/Laravel-Commentable#13]
Seems that entire Node class was removed from lazychaser/laravel-nestedset...

**Comment by tomiiide** [comment]
Have the same problem, did you fix it?

**Comment by ergonomicus** [comment]
@tomiiide I have removed laravel-commentable, then composer require "kalnoy/nestedset:4.1.6", then reuqired laravel-commentable again...

Hope that helps.

**Comment by jdfx** [comment]
@ergonomicus thanks, that solved it for me. I was about to give up on this package.

**Comment by andreScutieri** [comment]
The request still stands with Laravel 5.4. The new version of Kalnoy/Nestedset removed Node and changed it for NodeTrait. Trying to install a previous version of Nestedset (like 4.1.6) fails while using Laravel 5.4 because the Nestedset Package only allows for 5.2 or 5.3 version of Illuminate.

Using the NodeTrait fails to save with this error:

`TypeError: Return value of App\Post::comment() must be an instance of use BrianFaust\Commentable\Comment, boolean returned`

**Comment by ergonomicus** [comment]
@andreScutieri My mistake, I should have wrote that I was talking about Laravel 5.2 solution. This is still an issue for Laravel>5.2

**Comment by 58bits** [comment]
same problem - as described by @andreScutieri

**Comment by tomiiide** [comment]
Try using it like this in your models

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use BrianFaust\Commentable\HasCommentsTrait;
use BrianFaust\Commentable\Interfaces\HasComments;

class Post extends Model implements HasComments
{
  use HasCommentsTrait;
}
```

**Comment by andreScutieri** [comment]
Ok, I solved the problem. Here's how:

1. Install the latest `NestedSet` version, like so:

```
$ composer require kalnoy/nestedset
```

2. Change the `Comment` Model to use the NestedSet Trait instead of Node, like so:

``` php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Kalnoy\Nestedset\NodeTrait;

class Comment extends Model
{
    use NodeTrait;
...
```

3. Now in `HasComments` Trait we need to change a little bit of the `comment` and `updateComment` functions, changing the `$comment->appendTo` to the new `$comment->appendToNode`:

``` php
/**
     * @param $data
     * @param Model      $creator
     * @param Model|null $parent
     *
     * @return static
     */
    public function comment($data, Model $creator, Model $parent = null)
    {
        $commentableModel = $this->commentableModel();
        $comment = (new $commentableModel())->createComment($this, $data, $creator);
        if (!empty($parent)) {
            $comment->appendToNode($parent)->save();
        }
        return $comment;
    }
    /**
     * @param $id
     * @param $data
     * @param Model|null $parent
     *
     * @return mixed
     */
    public function updateComment($id, $data, Model $parent = null)
    {
        $commentableModel = $this->commentableModel();
        $comment = (new $commentableModel())->updateComment($id, $data);
        if (!empty($parent)) {
            $comment->appendToNode($parent)->save();
        }
        return $comment;
    }
```

4. Finally, we need to change a bit of code to avoid errors:

HasComments's `comment()` complains that we can't appendToNode when the Node is just `false` or `true`. That happens because in the Comment Model, the `createComment()` function returns a bool instead of an object. I don't know why the code is like that, and as I want a quick fix for it, I changed the `createComment()` function to this:

``` php
public function createComment(Model $commentable, $data, Model $creator)
    {
        $comment = new static();
        $comment->forceFill(array_merge($data, [
            'creator_id'   => $creator->id,
            'creator_type' => get_class($creator),
        ]));

        return $commentable->comments()->save($comment) ? $comment : false;
    }
```

Of course, you need to remove the enforced type or else it will try to return null. A mixed return like that is ugly as hell, but it's better than hearing the code complain all the time. Maybe the author would want to review this bit to something more palatable.

And that's it. Now Laravel Commentable works perfectly with NestedSet. I ran some unit tests and all returned good, so I'm not about to complain, even if the fix was a little messy. Hope you guys like it and thank you for your help.

**Comment by faustbrian** [comment]
Sorry for the late response, Github hasn't notified me about anything on here the last few weeks...

If some could send a PR with all the changes required I could keep a separate branch and release for people who require these changes.

**Comment by faustbrian** [comment]
@ergonomicus @tomiiide @jdfx @andreScutieri @58bits https://github.com/faustbrian/Laravel-Commentable/commit/76e3dce4a809abb526eb1f43d9144bc1d99129f9
https://github.com/faustbrian/Laravel-Commentable/releases/tag/2.1.2

Sorry for the long waiting time, as I said I have not received any emails from Github for almost 3 months.
