### ISSUE TITLE
appendTo() on boolean

### ISSUE THREAD

**Issue by jericopulvera** [faustbrian/Laravel-Commentable#16]
-PHP Version: 7.1

## Expected behavior:
creates child comment
## Actual behavior:
FatalThrowableError in HasComments.php line 60:
Call to a member function appendTo() on boolean
## Steps to reproduce the behavior:
```
     // Store method
     $post = Post::first();
     $parent = $post->comments->first();
       $comment = $post->comment([
           'title' => 'Some title',
           'body' => 'Some body',
       ], Auth::user(), $parent);

       dd($comment);
```

```
// HasComment Trait
public function comment($data, Model $creator, Model $parent = null)
    {
        $commentableModel = $this->commentableModel();

        $comment = (new $commentableModel())->createComment($this, $data, $creator); // This returns boolean.
       
        if (!empty($parent)) {
            $comment->appendTo($parent)->save();
        }

        return $comment;
    }
```
## Proposed solution:
Please tell me

**Comment by noxify** [comment]
@jericopulvera - And what was the problem? And how did you solved it?

**Comment by jericopulvera** [comment]
@noxify I forgot how I solve it. I just fiddled around with it. 
*I downloaded the latest version here on github then paste the src code on the vendors faustrbrian folder. 
* change ServiceProvider to AbstractServiceProvider.
*  the problem was this (new $commentableModel())->createComment($this, $data, $creator); // This returns boolean instead of a commentable model.

**Comment by leonelngande** [comment]
Not opening another issue since mine is same as this one.

Experienced this just now, actually it's been bothering me ever since I noticed the createComment and updateComment methods in the HasComments trait sometimes return a boolean and at other times return the created/updated comment.
![image](https://user-images.githubusercontent.com/13051253/62359198-37b09600-b50e-11e9-8abb-a50e4766d1ad.png)

@noxify how did you fix this please..? Am working with "artisanry/commentable": "4.0.0"

@faustbrian

**Comment by noxify** [comment]
Hi @leonelngande,

this issue is from 2017 - i can't remember what was the solution.

What you can try is the following:

1. Create your own `Comment` Model (Duplicate from https://github.com/artisanry/commentable/blob/master/src/Models/Comment.php)
2. Remove the `(bool)` in the `updateComment` method:
https://github.com/artisanry/commentable/blob/master/src/Models/Comment.php#L76
3. Instead of `update()` you have to use `updateOrCreate()` to get a valid collection/eloquent model/db entry
3. In the comments config you have to define your own model


references:
* https://laravel.com/api/5.8/Illuminate/Database/Eloquent/Builder.html#method_updateOrCreate
* https://laravel.com/api/5.8/Illuminate/Database/Eloquent/Builder.html#method_update

P.S. 
I did not test the solution above - it's just an idea based on what i have seen in the code.

Maybe it helps - Good Luck! :)

**Comment by leonelngande** [comment]
Thanks for the super quick response @noxify 
Was just about to submit a pull request to remove that boolean return type on the package's Comment model updateComment method, did some checking and came to the conclusion referenced in your point 3. above.

This however means the updateComment method on the HasComments trait has a faulty implementation given it tries to append a boolean (return value from comment model updateComment method) to the parent comment.

Will use you suggestion above as a quick fix, thanks again.

However the HasComments trait's `updateComment()` method issue has to be fixed. Changing the return type of the comment model's `updateComment` method might not be ok given others might already be making use of that boolean. 

Is something like this ok..?
```
trait HasComments
{
    // ...

/**
     * @param $id
     * @param $data
     * @param Model|null $parent
     *
     * @return mixed
     */
    public function updateComment($id, $data, Model $parent = null)
    {
        /** @var Model $parentComment */
        $commentableModel = $this->commentableModel();

        $comment = (new $commentableModel())->updateComment($id, $data);

        if (!empty($parent)) {
            $parent->appendNode($commentableModel::find($id));
        }

        return $comment;
    }
}
```

**Comment by leonelngande** [comment]
> **But I'm not sure if you will have some unexpected side effects with this idea - you have to check the package, that the boolean value is not required in another method or so.**

Just verified and the boolean is used only in the HasComments.php `updateComment()` method of the package, [here](https://github.com/artisanry/commentable/blob/b0fa481906cf7af95e416e98e14b02de73323c17/src/Traits/HasComments.php#L69).

**Comment by noxify** [comment]
Alternative keep it as it is and create a new method which runs the `updateComment` method.
If the return from `updateComment` is `true` you select the comment again via

```
        $comment = (new $commentableModel())->find($id);
```

Another idea is to add an argument to the existing `updateComment` if this argument is `true` you will return the model instead of the boolean value.
With this, the existing implementation is working and you can decide which return value you want.

And yes, you're right - The Trait needs to be updated, too.

**Comment by leonelngande** [comment]
> Another idea is to add an argument to the existing `updateComment` if this argument is `true` you will return the model instead of the boolean value.
> With this, the existing implementation is working and you can decide which return value you want.

Ok, thought of something like this too. Will submit a pull request with one of those implementations. Thanks @noxify 

Hopefully, @faustbrian is ok with this change..
